OpenZeppelin/rust-contracts-stylus

Cargo.lock
contracts/Cargo.toml
contracts/src/token/erc721/extensions/burnable.rs
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/mod.rs

ref: use msg::sender directly in tests (#89)

---

.github/workflows/e2e-tests.yml

Follow-up to #114 
Removes the end-to-end tests coverage workflow until we have a clearer idea of how to make it work, which may entail delegating to the Stylus codebase.
The rationale is: `llvm-cov` instruments binaries in order to collect data used in computing coverage. The output of the instrumented binaries is written to the filesystem, and then uploaded to codecov.io.
Writing to the filesystem is not an operation allowed in the sandboxed webassembly environment where contracts run, namely, the host (Stylus VM).

fix(ci): remove useless coverage workflow

---

Cargo.lock
contracts/src/access/control.rs
contracts/src/access/ownable.rs
contracts/src/token/erc20/extensions/capped.rs
contracts/src/token/erc20/mod.rs
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/extensions/uri_storage.rs
contracts/src/token/erc721/mod.rs
contracts/src/utils/pausable.rs
lib/motsu-proc/Cargo.toml
lib/motsu-proc/src/default_storage_layout.rs
lib/motsu-proc/src/lib.rs
lib/motsu-proc/src/stylus_default.rs
lib/motsu-proc/src/test.rs
lib/motsu-proc/tests/default.rs
lib/motsu/src/lib.rs

Resolves #51 
This PR implements a custom derive macro for Default inside `motsu-proc` crate that makes it available inside all unit tests. This follows the rules of solidity storage and only works with  `sol_storage!` structs for now.
- All places where Default was implemented were updated and tests are passing

feat: custom derive macro for Default

---

.github/workflows/e2e-tests.yml

E2e pipeline forcing recompilation and deps download when we open a new pr despite caching step.
Cache hit still occurs and stale cache retrieved. Since cache hit happened new (valid) cache won't be saved. So it doesn't help after consecutive pushes. 
Just cache reset forces cargo cache to be persisted and it works faster after.
This pr basically adds caching for `e2e` test per scope of pull request (pr id).
And if it wasn't found (like pr just opened) should try retrieve a cache with the same hash of `Cargo.lock` file and persist new cache per pr id.
Will see how it will work.

fix(ci): cache rust dependencies per pr

---

.github/workflows/check-wasm.yml
.github/workflows/e2e-tests.yml

Experimental github action cache pr.
Replace caching steps in gh e2e workflow with [rust-cache gh action](https://github.com/marketplace/actions/rust-cache).
This action workflow also used by [alloy-rs](https://github.com/alloy-rs/core/blob/main/.github/workflows/ci.yml).

ci: rust-cache gh action

---

.github/scripts/check-wasm.sh
.github/workflows/check-wasm.yml
.github/workflows/e2e-tests.yml
Cargo.lock
Cargo.toml
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/mod.rs
lib/e2e/src/deploy.rs
lib/motsu/src/shims.rs
scripts/e2e-tests.sh
scripts/nitro-testnode.sh

Resolves #57 
Now that `nitro-testnode` has been updated, we are safe to bump the SDK version.

build: bump sdk to v0.5.0

---

contracts/src/token/erc20/extensions/burnable.rs
contracts/src/token/erc20/extensions/capped.rs
contracts/src/token/erc20/mod.rs
contracts/src/token/erc721/extensions/burnable.rs
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/mod.rs
contracts/src/utils/structs/bitmap.rs
examples/erc20/tests/erc20.rs
examples/erc721/tests/erc721.rs
lib/motsu-proc/tests/default.rs

Curious why we are not using const evaluation for alloy number types wherever is possible?

chore: enforce uint macro for const evaluation

---

.github/workflows/test.yml

This is super minor, but I noticed that on the description of this workflow we say that we have a job called `minimal` but we don't.

docs(ci): remove minimal from workflow description

---

lib/motsu-proc/src/default_storage_layout.rs

If once we will need to use contracts with generic params. DefaultStorageMacro will work with them from now on.

fix: default storage macro with generically typed contracts

---

.github/workflows/check.yml
Cargo.lock
Cargo.toml
benches/Cargo.toml
benches/src/erc20.rs
benches/src/lib.rs
benches/src/main.rs
contracts/src/token/erc20/mod.rs
contracts/src/utils/pausable.rs
lib/e2e/src/account.rs
lib/e2e/src/lib.rs
lib/e2e/src/system.rs

Resolves #167 
Initial work towards having a full gas benchmarking suite.
It's tested running against `nitro-testnode`, but should be good to test against Arbitrum Sepolia or any other Stylus-enabled RPC endpoint.
The output looks like this:
You can see that the `L1 Gas` is 0, and this is because of the configuration of `nitro-testnode`, for a testnet like Arbitrum Sepolia this number would be different than zero most of the time.
Note that we need to deserialize the extra fields of the transaction receipt in order to access the gas usage in the L1.
```rust
#[derive(Debug, Deserialize)]
struct ArbOtherFields {
#[serde(rename = "gasUsedForL1")]
gas_used_for_l1: U128,
#[allow(dead_code)]
#[serde(rename = "l1BlockNumber")]
l1_block_number: String,
}
```

feat: benchmark ERC-20 gas usage

---

examples/erc20/tests/erc20.rs
examples/ownable/tests/ownable.rs
lib/e2e/src/event.rs

Small refactor to enable checking an event does *not* get emitted.
I'm currently working on the e2e tests for `AccessControl` and had the need to check that an event was not emitted. However, with the current API of `receipt.emits`, the assertion occurs inside the `emits` function, which does not let me do something like `assert!(!receipt.emits(...));`.
This PR enables this by delegating the assertion to the caller.
This also makes the API more consistent with the Error e2e API.

feat(e2e): enable checking whether an event was not emitted

---

README.md
contracts/src/access/control.rs
contracts/src/access/ownable.rs
contracts/src/lib.rs
contracts/src/token/erc20/extensions/burnable.rs
contracts/src/token/erc20/extensions/metadata.rs
contracts/src/token/erc721/extensions/burnable.rs
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/extensions/metadata.rs
contracts/src/token/erc721/mod.rs
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/access-control.adoc
lib/crypto/src/lib.rs
lib/crypto/src/merkle.rs

Resolves #206 & #12 
There are quite a few changes besides what one would expect because I fixed all the broken links in the contract's crate after adding `#![deny(rustdoc::broken_intra_doc_links)]`.

feat(docs): document Ownable

---

docs/modules/ROOT/pages/crypto.adoc

feat(docs): document the merkle proof verifier functions

---

contracts/src/token/erc721/mod.rs
examples/erc721/tests/erc721.rs

Resolves #224 
The `FIXME`s added in the PR are tracked [here](https://github.com/OpenZeppelin/rust-contracts-stylus/issues/228).

fix(erc721): properly handle receiver errors

---

Cargo.toml

Need to pin so that new installs don't use broken versions.

build: pin stylus-sdk version

---

contracts/src/access/control.rs

Since this test is incomplete and we already cover this feature in e2e tests, we remove it.

ref: remove incomplete test covered in e2e

---

Cargo.lock
examples/access-control/tests/access_control.rs
examples/ecdsa/tests/ecdsa.rs
examples/erc20-permit/tests/erc20permit.rs
examples/erc20/tests/erc20.rs
examples/erc721-consecutive/tests/erc721-consecutive.rs
examples/erc721-metadata/tests/erc721.rs
examples/erc721/tests/erc721.rs
examples/ownable/tests/ownable.rs
lib/e2e/Cargo.toml
lib/e2e/README.md
lib/e2e/src/account.rs
lib/e2e/src/deploy.rs
lib/e2e/src/lib.rs

Adds `Account::as_deployer()` function that let's to configure contract (with/without constructor) for e2e tests. And deploy it.
Includes all necessary migrations of e2e tests to the new api.

ref(e2e): use generic deploy function

---

Cargo.lock
examples/merkle-proofs/Cargo.toml
examples/merkle-proofs/src/lib.rs
lib/crypto/Cargo.toml
lib/crypto/src/hash.rs
lib/crypto/src/merkle.rs

Decided to go for `openzeppelin-crypto-rs`, but obv open to something different.
UPDATE: In the end went for `openzeppelin-crypto`.

feat: rename crypto crate

---

contracts/src/token/erc20/extensions/burnable.rs
contracts/src/token/erc20/extensions/permit.rs
contracts/src/token/erc20/mod.rs
contracts/src/token/erc721/extensions/burnable.rs
contracts/src/token/erc721/extensions/consecutive.rs
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/mod.rs
contracts/src/utils/cryptography/ecdsa.rs
contracts/src/utils/mod.rs
contracts/src/utils/structs/checkpoints.rs

Allows to the library users to reuse our traits with their own error types.
And it is more "rusty" approach having associated error types for traits with fallible functions.
Adds new functional macro for the `MethodError` trait.

ref: add associated error types for contract traits

---

docs/antora.yml
docs/modules/ROOT/pages/index.adoc

Add the rc tag to the docs so we can publish them before the audit. It should be shown as `0.1.0-rc` on the site. I also made clear in the warning that this hasn't been audited yet.

Add rc tag to antora docs and improve security warning in docs

---

examples/ecdsa/src/constructor.sol
lib/e2e/src/deploy.rs

This PR changes the `e2e` testing library to allow deployments of contracts without a constructor., when the constructor file is not present. This is already allowed by [koba](https://github.com/OpenZeppelin/koba/blob/main/src/generator.rs#L27-L30).
~Resolves #???~

fix(e2e): deploy contracts without Solidity constructor when not needed

---

contracts/src/token/erc721/extensions/consecutive.rs
contracts/src/token/erc721/mod.rs

Adds missing tests to erc721 consecutive mostly associated with erc721 standard's operations.

tests: increase code coverage at consecutive

---

.github/workflows/gas-bench.yml
Cargo.lock
Cargo.toml
benches/Cargo.toml
benches/src/access_control.rs
benches/src/erc20.rs
benches/src/erc721.rs
benches/src/lib.rs
benches/src/main.rs
benches/src/merkle_proofs.rs
benches/src/report.rs
lib/e2e/src/account.rs
lib/e2e/src/system.rs
scripts/bench.sh
scripts/nitro-testnode.sh

Use the `cargo stylus cache` to cache contracts in the `CacheManager` before running benches.

feat: cache contracts before benching

---

.github/workflows/check-publish.yml
Cargo.lock
Cargo.toml
contracts-proc/Cargo.toml
contracts-proc/src/interface.rs
contracts-proc/src/interface_id.rs
contracts-proc/src/lib.rs
contracts/Cargo.toml
contracts/src/token/erc20/extensions/metadata.rs
contracts/src/token/erc20/mod.rs
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/extensions/metadata.rs
contracts/src/token/erc721/mod.rs
contracts/src/utils/introspection/erc165.rs
contracts/src/utils/introspection/mod.rs
contracts/src/utils/mod.rs
examples/erc20/src/lib.rs
examples/erc20/tests/abi/mod.rs
examples/erc20/tests/erc20.rs
examples/erc721/src/lib.rs
examples/erc721/tests/abi/mod.rs
examples/erc721/tests/erc721.rs

Adds erc165 standard altogether with a proc macro, that lets to compute interface id in a simple way.
Resolves #33

feat: erc165 support interface

---

contracts-proc/Cargo.toml

Due to automerge `openzeppelin-stylus-proc` crate is using keywords from the workspace and breaks the build.

fix: update keywords for contracts-proc

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/utilities.adoc

docs: erc165 + structs

---

.github/workflows/check-links.yml
.linkspector.yml
docs/modules/ROOT/pages/access-control.adoc
docs/modules/ROOT/pages/crypto.adoc
docs/modules/ROOT/pages/erc20-burnable.adoc
docs/modules/ROOT/pages/erc20-capped.adoc
docs/modules/ROOT/pages/erc20-metadata.adoc
docs/modules/ROOT/pages/erc20-pausable.adoc
docs/modules/ROOT/pages/erc20-permit.adoc
docs/modules/ROOT/pages/erc20.adoc
docs/modules/ROOT/pages/erc721-burnable.adoc
docs/modules/ROOT/pages/erc721-consecutive.adoc
docs/modules/ROOT/pages/erc721-enumerable.adoc
docs/modules/ROOT/pages/erc721-metadata.adoc
docs/modules/ROOT/pages/erc721-pausable.adoc
docs/modules/ROOT/pages/erc721-uri-storage.adoc
docs/modules/ROOT/pages/erc721.adoc

Fixes #299 
- We have to include the version because the default one is empty(until we publish 0.1.0 at least), but anyways it is important to explicitly include the version.
- Add crate suffix after version, otherwise the link is still broken
- Fix crypto urls
- Add GH workflow that checks that links are not broken on `adoc`and `md` files :)

fix: docs.rs url

---

contracts/src/utils/pausable.rs
examples/erc20/src/lib.rs
examples/erc20/tests/abi/mod.rs
examples/erc20/tests/erc20.rs
examples/erc721/src/lib.rs
examples/erc721/tests/abi/mod.rs
examples/erc721/tests/erc721.rs

Methods `pause` and `unpause` are not exposed by default now.
Resolves #314

fix(L-04): Public Exposure of pause and unpause Functions

---

contracts/src/utils/pausable.rs

Resolves #318 
I used the term `helpers`, but open to better wording if someone has suggestions. This touches the same file as #311, so we might need to update it after we merge that one.

fix(N-05) improve comments for modifiers

---

contracts/src/token/erc20/extensions/burnable.rs
contracts/src/token/erc20/extensions/permit.rs
contracts/src/token/erc20/mod.rs

Add additional check to `approve` + emit_event flag like in solidity. Rely on that `approve` inside `_spend_allowance`.
Resolves #313

fix(L-03): Missing Checks in ERC-20 Implementation

---

.cargo/config.toml
.github/workflows/check-publish.yml
.github/workflows/check-wasm.yml
.github/workflows/check.yml
.github/workflows/e2e-tests.yml
.github/workflows/gas-bench.yml
.github/workflows/nostd.yml
.github/workflows/test.yml
contracts/src/token/erc721/mod.rs
rust-toolchain.toml
scripts/bench.sh
scripts/check-wasm.sh
scripts/e2e-tests.sh

It seems that reference types from WASM are not supported by `wasm-parser` crate (https://github.com/rustwasm/wasm-bindgen/issues/4211).
It makes us pin to the recent nightly toolchain version that works, and contribution experience gets quite convoluted.
Hopefully there is an option to disable `reference-types` with a flag: `-C target-cpu=mvp` for `wasm32-unknown-unknown` target.
Resolves #374
Single source of rust toolchain from `rust-toolchain.toml` added for ci pipelines (actions-rust-lang/setup-rust-toolchain@v1 gh action used for that).
Resolves #294

fix: reference-types error on nightly version

---

GUIDELINES.md

This was the minimum amount of steps that took me to set up the repo and successfully run e2e tests

docs: add short setup guide to GUIDELINES.md

---

CHANGELOG.md
contracts/src/access/control.rs
contracts/src/access/ownable.rs
contracts/src/access/ownable_two_step.rs
contracts/src/finance/vesting_wallet.rs
contracts/src/token/erc1155/extensions/metadata_uri.rs
contracts/src/token/erc1155/extensions/supply.rs
contracts/src/token/erc1155/extensions/uri_storage.rs
contracts/src/token/erc1155/mod.rs
contracts/src/token/erc20/extensions/capped.rs
contracts/src/token/erc20/extensions/metadata.rs
contracts/src/token/erc20/mod.rs
contracts/src/token/erc721/extensions/consecutive.rs
contracts/src/token/erc721/extensions/enumerable.rs
contracts/src/token/erc721/extensions/metadata.rs
contracts/src/token/erc721/extensions/uri_storage.rs
contracts/src/token/erc721/mod.rs
contracts/src/utils/math/storage.rs
contracts/src/utils/metadata.rs
contracts/src/utils/nonces.rs
contracts/src/utils/pausable.rs
contracts/src/utils/structs/bitmap.rs
contracts/src/utils/structs/checkpoints/mod.rs
examples/erc1155/src/lib.rs
examples/erc20/src/lib.rs
examples/erc721/src/lib.rs
lib/crypto/src/poseidon2/mod.rs
lib/e2e/README.md
lib/e2e/src/account.rs
scripts/e2e-tests.sh

ref: Add/Sub Assignment Operations + e2e-tests.sh

---

examples/erc721/src/lib.rs
examples/erc721/tests/abi/mod.rs
examples/erc721/tests/erc721.rs

test: add missing E2E tests for Erc721

---

.github/workflows/check-wasm.yml
.github/workflows/e2e-tests.yml
.github/workflows/gas-bench.yml
CHANGELOG.md
scripts/nitro-testnode.sh

- Bump cargo-stylus to [`v0.5.8`](https://github.com/OffchainLabs/cargo-stylus/releases/tag/v0.5.8).
- Bump nitro-testnode to https://github.com/OffchainLabs/nitro-testnode/commit/af851769d52cab38bc3733dbd0a4db6120fa7864.

build: cargo stylus v0.5.8

---

lib/crypto/src/field/fp.rs
lib/crypto/src/hash.rs
lib/crypto/src/keccak.rs
lib/crypto/src/lib.rs
lib/crypto/src/merkle.rs
lib/crypto/src/test_helpers.rs

Making all prop tests stand-alone is helpful as it enables devs using certain IDEs to run each test individually by clicking an appropriate button that appears next to individual tests

ref: make all proptests stand-alone + replace prop_assume calls with helper fn

---

CHANGELOG.md
contracts/src/access/ownable_two_step.rs
contracts/src/token/erc20/extensions/permit.rs
examples/ownable-two-step/src/lib.rs

This will allow devs to implement a `permit + burnable` combination without accessing the nested `Erc20Permit.erc20` instance.
Implementing `Deref`:
- makes the implementation more intuitive.
- makes implementing Wizard's function printing logic more straightforward ([current](https://github.com/OpenZeppelin/contracts-wizard/blob/76dee5295d843c227b0d24c4f78cf62d1933d427/packages/core/stylus/src/erc20.ts#L220-L225) VS [if this PR is merged](https://github.com/OpenZeppelin/contracts-wizard/blob/b536968c1a3b3ba91c5f2217b22ffa946cc7d789/packages/core/stylus/src/erc20.ts#L218-L223))
```rust
// other imports...
use openzeppelin_stylus::{
token::erc20::extensions::{Erc20Permit, IErc20Burnable},
utils::cryptography::eip712::IEip712,
};
#[entrypoint]
#[storage]
struct Erc20PermitExample { …
```

feat: implement Deref for Erc20Permit and Ownable2Step

---

contracts/src/access/control.rs

fix: clippy warning in AccessControl

---

rust-toolchain.toml

This nightly channel is post-Rust-1.87.0, which is [default](https://github.com/OffchainLabs/stylus-hello-world/blob/5b3fa18f70ff58b8964b089be688f9616de54499/rust-toolchain.toml) for new Stylus projects.

build: Fix failing cargo-stylus@0.6.0 install -> bump nightly channel to 2025-06-03 

---

lib/crypto/src/arithmetic/limb.rs
lib/crypto/src/arithmetic/uint.rs
lib/crypto/src/field/fp.rs

Fixes L-02: Inconsistent Data Types for carry and borrow Parameters

fix(audit): L-02: Inconsistent Data Types for carry and borrow Parameters

---

lib/e2e/src/deploy.rs
scripts/bench.sh
scripts/e2e-tests.sh
scripts/nitro-testnode.sh

We need to update the nitro-testnode as the CI jobs started failing, like in #716.

build(ci): update nitro-testnode

---

CHANGELOG.md
lib/crypto/src/arithmetic/uint.rs
lib/crypto/src/eddsa.rs
lib/crypto/src/field/fp.rs

This pr doesn't add equality checks, but ensures that modulus will be the same for WideScalar

fix(N-04): Missing Checks for Equality of Scalar and WideScalar in EdDSA
