OpenZeppelin/rust-contracts-stylus

Cargo.lock, contracts/Cargo.toml, examples/access-control/Cargo.toml, examples/access-control/src/lib.rs, examples/erc20/Cargo.toml, examples/erc20/src/lib.rs, examples/erc721/Cargo.toml, examples/erc721/src/lib.rs, examples/ownable/Cargo.toml, examples/ownable/src/lib.rs
I just realized that we do not use proper library name in examples.
=> ref: use proper library name

Cargo.lock, Cargo.toml, lib/e2e/src/system.rs, lib/e2e/src/user.rs
=> feat: use v0.1.1 of alloy from crates.io

.github/workflows/e2e-tests.yml, examples/erc20/src/lib.rs, examples/erc20/tests/abi.rs, examples/erc20/tests/erc20.rs, examples/erc721/tests/abi.rs, examples/erc721/tests/erc721.rs, lib/e2e/src/error.rs, lib/e2e/src/lib.rs
=> test(erc20): add integration tests

.github/workflows/check-wasm.yml, .github/workflows/e2e-tests.yml, Cargo.lock, lib/e2e/Cargo.toml
=> feat: use v0.1.0 of koba from crates.io

.github/workflows/check-wasm.yml
=> chore: remove outdated comment

Cargo.lock, contracts/src/access/ownable.rs, examples/erc20/tests/erc20.rs, examples/ownable/Cargo.toml, examples/ownable/tests/abi.rs, examples/ownable/tests/ownable.rs
=> feat(e2e): add Ownable tests

Cargo.toml, contracts/Cargo.toml, examples/erc20/Cargo.toml, examples/erc721/Cargo.toml, examples/ownable/Cargo.toml, lib/crypto/Cargo.toml, lib/e2e-proc/Cargo.toml, lib/e2e/Cargo.toml, lib/motsu-proc/Cargo.toml, lib/motsu/Cargo.toml
Moved all dependency importation to the root workspace `Cargo.toml` and referenced it at the crate level.
Resolves #144
=> ref: aggregate deps in root manifest

Cargo.lock, examples/access-control/Cargo.toml, examples/access-control/src/lib.rs, examples/access-control/tests/abi.rs, examples/access-control/tests/access_control.rs
=> feat(access): add AccessControl e2e tests

lib/motsu/src/context.rs, lib/motsu/src/storage.rs
=> fix: solve clippy warnings (#193)

Cargo.lock, Cargo.toml, benches/src/access_control.rs, benches/src/erc20.rs, benches/src/lib.rs, benches/src/main.rs, benches/src/merkle_proofs.rs, examples/basic/script/src/main.rs, lib/e2e/src/account.rs, lib/e2e/src/deploy.rs
=> feat: bench merkle proofs verification gas usage

benches/src/access_control.rs, benches/src/erc20.rs, benches/src/erc721.rs, benches/src/lib.rs, benches/src/main.rs
=> feat: bench Erc721 gas usage

benches/src/access_control.rs, benches/src/erc20.rs, benches/src/erc721.rs, benches/src/lib.rs, benches/src/main.rs, benches/src/merkle_proofs.rs, benches/src/report.rs
=> ref: rework gas usage reporting

.github/workflows/gas-bench.yml, benches/src/access_control.rs, benches/src/erc20.rs, benches/src/erc721.rs, benches/src/lib.rs, benches/src/main.rs, benches/src/merkle_proofs.rs, benches/src/report.rs, scripts/bench.sh, scripts/e2e-tests.sh
=> feat(ci): add gas-benching workflow

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/erc20.adoc, docs/modules/ROOT/pages/erc721.adoc, docs/modules/ROOT/pages/tokens.adoc
=> feat(docs): document erc20

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/deploy.adoc
=> feat(docs): document deploying contracts

examples/access-control/tests/access_control.rs, examples/erc20/tests/erc20.rs, examples/erc721-metadata/tests/erc721.rs, examples/ownable/tests/ownable.rs, lib/e2e/src/deploy.rs
=> test: assert errors during contract deployment

Cargo.lock, contracts/Cargo.toml, lib/crypto/Cargo.toml
=> build: bump version to 0.1.0-rc

.github/workflows/e2e-tests.yml, .github/workflows/gas-bench.yml, GUIDELINES.md, lib/e2e/src/system.rs, scripts/e2e-tests.sh, scripts/nitro-testnode.sh
Extend guidelines for e2e tests and adjust ux of few scripts.
=> docs: e2e tests setup guide

README.md
- Specify crates.io as the main source for the library
=> Update readme to specify crates.io as the source

contracts/src/token/erc20/extensions/metadata.rs, contracts/src/token/erc721/extensions/enumerable.rs, contracts/src/token/erc721/mod.rs
Resolves #315 
I'm leaving comments on things that might need some discussion
=> fix(N-01) Remove TODOs and FixMes

contracts/src/utils/cryptography/ecdsa.rs
=> fix(L-05): remove redundant error from ECDSA smart contract

.github/workflows/check-links.yml, .github/workflows/check-publish.yml, Cargo.lock, Cargo.toml, contracts-proc/Cargo.toml, contracts/Cargo.toml, docs/modules/ROOT/pages/crypto.adoc
=> fix: cannot publish packages to crates.io

docs/antora.yml, docs/modules/ROOT/pages/access-control.adoc, docs/modules/ROOT/pages/crypto.adoc, docs/modules/ROOT/pages/erc20-burnable.adoc, docs/modules/ROOT/pages/erc20-capped.adoc, docs/modules/ROOT/pages/erc20-metadata.adoc, docs/modules/ROOT/pages/erc20-pausable.adoc, docs/modules/ROOT/pages/erc20-permit.adoc, docs/modules/ROOT/pages/erc20.adoc, docs/modules/ROOT/pages/erc721-burnable.adoc, docs/modules/ROOT/pages/erc721-consecutive.adoc, docs/modules/ROOT/pages/erc721-enumerable.adoc, docs/modules/ROOT/pages/erc721-metadata.adoc, docs/modules/ROOT/pages/erc721-pausable.adoc, docs/modules/ROOT/pages/erc721-uri-storage.adoc, docs/modules/ROOT/pages/erc721.adoc
=> docs: update Antora docs for v0.1.0

.github/workflows/check-links.yml, .github/workflows/check-publish.yml, .github/workflows/check-wasm.yml, .github/workflows/check.yml, .github/workflows/e2e-tests.yml, .github/workflows/gas-bench.yml, .github/workflows/nostd.yml, .github/workflows/publish-motsu-proc.yml, .github/workflows/publish-motsu.yml, .github/workflows/publish-openzeppelin-crypto.yml, .github/workflows/publish-openzeppelin-stylus-proc.yml, .github/workflows/publish-openzeppelin-stylus.yml, .github/workflows/test.yml
=> build: add CI release automation

benches/src/lib.rs, benches/src/main.rs, benches/src/ownable.rs
=> feat: Gas benches for Ownable

README.md, contracts/src/lib.rs, docs/modules/ROOT/pages/index.adoc
https://github.com/OpenZeppelin/rust-contracts-stylus/actions/runs/12284242525/job/34279570019
=> docs: fix stylus gentle intro link

examples/erc1155/tests/abi/mod.rs, examples/erc1155/tests/erc1155.rs, examples/erc721/tests/abi/mod.rs, examples/erc721/tests/erc721.rs
Addresses https://github.com/OpenZeppelin/rust-contracts-stylus/pull/479#discussion_r1910238823
=> test: change Panic error's arg name to 'code'

GUIDELINES.md, contracts/src/token/erc1155/mod.rs, contracts/src/token/erc721/mod.rs, docs/modules/ROOT/pages/deploy.adoc
Avoids the links breaking from under us
=> docs: use fixed versions in solidity docs URLs

contracts/src/token/erc1155/receiver.rs, contracts/src/token/erc721/extensions/consecutive.rs, contracts/src/token/erc721/mod.rs, contracts/src/token/erc721/receiver.rs
=> ref: improve Erc1155Receiver and Erc721Receiver

CHANGELOG.md, contracts/src/token/erc1155/extensions/supply.rs, contracts/src/token/erc721/extensions/consecutive.rs
Need this for the same reasons as https://github.com/OpenZeppelin/rust-contracts-stylus/pull/552
Resolves #565
=> feat: Implement `Deref<Target = Erc1155>` for `Erc1155Supply` and `Deref<Target = Erc721>` for `Erc721Consecutive`

docs/modules/ROOT/pages/finance.adoc, docs/modules/ROOT/pages/vesting-wallet.adoc
=> docs: add Antora docs for VestingWallet

CHANGELOG.md, contracts/src/access/control.rs, contracts/src/access/ownable.rs, contracts/src/finance/vesting_wallet.rs, contracts/src/token/common/erc2981.rs, contracts/src/token/erc1155/extensions/metadata_uri.rs, contracts/src/token/erc1155/receiver.rs, contracts/src/token/erc20/extensions/capped.rs, contracts/src/token/erc20/extensions/erc4626.rs, contracts/src/token/erc20/extensions/flash_mint.rs, contracts/src/token/erc20/extensions/metadata.rs, contracts/src/token/erc20/extensions/permit.rs, contracts/src/token/erc20/mod.rs, contracts/src/token/erc20/utils/mod.rs, contracts/src/token/erc20/utils/safe_erc20.rs, contracts/src/token/erc721/extensions/consecutive.rs, contracts/src/token/erc721/extensions/enumerable.rs, contracts/src/token/erc721/extensions/metadata.rs, contracts/src/token/erc721/receiver.rs, contracts/src/utils/cryptography/ecdsa.rs, contracts/src/utils/metadata.rs, contracts/src/utils/nonces.rs, contracts/src/utils/pausable.rs, examples/merkle-proofs/src/lib.rs
=> refactor: optimize Stylus SDK imports

CONTRIBUTING.md, Cargo.toml, README.md, contracts/src/token/erc1155/mod.rs, lib/crypto/src/merkle.rs
=> docs: update Contribution Guidelines

CHANGELOG.md, contracts/src/access/control.rs, contracts/src/access/ownable.rs, contracts/src/finance/vesting_wallet.rs, contracts/src/token/erc1155/extensions/metadata_uri.rs, contracts/src/token/erc1155/mod.rs, contracts/src/token/erc20/extensions/erc4626.rs, contracts/src/token/erc20/mod.rs, contracts/src/token/erc721/extensions/consecutive.rs, contracts/src/token/erc721/extensions/uri_storage.rs, contracts/src/token/erc721/mod.rs, contracts/src/utils/pausable.rs
Also add missing erc20 event asserts
=> feat: Derive Missing `Debug` Traits for Events

contracts/src/token/erc20/extensions/burnable.rs, contracts/src/token/erc20/extensions/erc4626.rs, contracts/src/token/erc20/extensions/flash_mint.rs, contracts/src/token/erc20/extensions/wrapper.rs, contracts/src/token/erc20/mod.rs
=> ref: use motsu_unwrap/motsu_expect in erc20 tests

Cargo.lock, benches/Cargo.toml, benches/src/access_control.rs, benches/src/erc1155_metadata_uri.rs, benches/src/erc20.rs, benches/src/ownable.rs, benches/src/vesting_wallet.rs
=> chore: Benches ref

lib/crypto/src/arithmetic/uint.rs
Fixes L-04: Absence of Overflow Check in from_str_hex Function
=> fix(audit): L-04: Absence of Overflow Check in from_str_hex Function

contracts/src/token/erc20/extensions/erc4626.rs, contracts/src/utils/structs/enumerable_set/mod.rs
Increases contract code coverage to 95%
=> test: Add `Erc4626` unit tests

benches/src/eddsa.rs, benches/src/lib.rs, benches/src/main.rs
Benchmark for eddsa signature verification.
=> feat: add eddsa benchmark

.github/workflows/check-abi.yml, .github/workflows/check-wasm.yml, .github/workflows/check.yml, .github/workflows/e2e-tests.yml, .github/workflows/fuzz.yml, .github/workflows/gas-bench.yml, .github/workflows/test.yml, rust-toolchain.toml
Related https://github.com/OpenZeppelin/rust-contracts-stylus/pull/818
=> build: bump rust and cargo-stylus versions

CHANGELOG.md, contracts/src/access/ownable.rs, contracts/src/access/ownable_two_step.rs, contracts/src/proxy/beacon/upgradeable.rs, docs/modules/ROOT/pages/beacon-proxy.adoc, docs/modules/ROOT/pages/uups-proxy.adoc, examples/ownable/src/lib.rs, examples/upgradeable-beacon/src/lib.rs, examples/uups-proxy-new-version/src/lib.rs, examples/uups-proxy/src/lib.rs
=> feat: add back assoc. error type to IOwnable
